# Generated by Django 5.2.9 on 2026-01-01 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('must', 'Must'), ('want', 'Want')], max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('dropped', 'Dropped')], default='pending', max_length=10)),
                ('sync_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('order', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
